--
-- This file is part of TALER
-- Copyright (C) 2024 Taler Systems SA
--
-- TALER is free software; you can redistribute it and/or modify it under the
-- terms of the GNU General Public License as published by the Free Software
-- Foundation; either version 3, or (at your option) any later version.
--
-- TALER is distributed in the hope that it will be useful, but WITHOUT ANY
-- WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
-- A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License along with
-- TALER; see the file COPYING.  If not, see <http://www.gnu.org/licenses/>

BEGIN;

SELECT _v.register_patch('libeufin-nexus-0003', NULL, NULL);

SET search_path TO libeufin_nexus;

CREATE TABLE IF NOT EXISTS talerable_outgoing_transactions
  (talerable_outgoing_transaction_id INT8 GENERATED BY DEFAULT AS IDENTITY UNIQUE
   ,initiated_outgoing_transaction_id INT8 UNIQUE REFERENCES initiated_outgoing_transactions(initiated_outgoing_transaction_id) ON DELETE CASCADE
   ,outgoing_transaction_id INT8 UNIQUE REFERENCES outgoing_transactions(outgoing_transaction_id) ON DELETE CASCADE
   ,CONSTRAINT tx_link CHECK (initiated_outgoing_transaction_id IS NOT NULL OR outgoing_transaction_id IS NOT NULL)
   ,request_uid BYTEA UNIQUE CHECK (LENGTH(request_uid)=64)
   ,wtid BYTEA NOT NULL UNIQUE CHECK (LENGTH(wtid)=32)
   ,exchange_base_url TEXT NOT NULL
  );
COMMENT ON COLUMN talerable_outgoing_transactions.initiated_outgoing_transaction_id
  IS 'If the transaction have been initiated';
COMMENT ON COLUMN talerable_outgoing_transactions.outgoing_transaction_id
  IS 'If the transaction have been recovered';
COMMENT ON CONSTRAINT tx_link ON talerable_outgoing_transactions
  IS 'A transaction is either initiated or recovered';

COMMIT;
