FROM docker.io/library/debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive
# Persistent gradle cache
ENV GRADLE_USER_HOME=/workdir/.gradle

RUN apt-get update -yqq && \
    apt-get install -yqq \
		           unzip \
		           openjdk-17-jdk-headless \
                   make \
                   python3-distutils \
                   po-debconf \
                   build-essential \
                   debhelper-compat \
                   devscripts \
		           git-buildpackage \
                   postgresql \
                   sudo

WORKDIR /workdir

CMD ["bash", "/workdir/ci/ci.sh"]
