FROM docker.io/library/debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -yqq && \
    apt-get install -yqq \
		   unzip \
		   openjdk-17-jdk \
		   openjdk-17-jdk-headless \
                   make \
                   git \
                   python3-distutils \
		   curl \
                   wget \
                   po-debconf \
                   build-essential \
                   debhelper-compat \
                   devscripts \
		   git-buildpackage \
                   postgresql \
                   sudo \
                   jq

# Note: not sure if we need curl/wget/jq at all!

WORKDIR /workdir

CMD ["bash", "/workdir/ci/ci.sh"]
