#!/bin/bash

set -eu

# Get database settings from dbconfig-common and write Taler configuration files.
if [ -f /etc/dbconfig-common/taler-libeufin.conf ]; then
  . /etc/dbconfig-common/taler-libeufin.conf
  case "$dbc_dbtype" in
  pgsql)
    # We assume ident auth here.  We might support password auth later.
    echo -e "LIBEUFIN_NEXUS_DB_CONNECTION=jdbc:postgres:///${dbc_dbname}\n\n" >> \
	 /etc/libeufin/nexus.env
    echo -e "LIBEUFIN_SANDBOX_DB_CONNECTION=jdbc:postgres:///${dbc_dbname}\n\n" >> \
	 /etc/libeufin/sandbox.env
   

    # Allow the libeufin-sandbox/nexus user to create schemas, needed by dbinit
    echo "GRANT CREATE ON DATABASE \"${dbc_dbtype}\" TO \"libeufin-nexus\";" | sudo -u postgres psql -f -
    echo "GRANT CREATE ON DATABASE \"${dbc_dbtype}\" TO \"libeufin-sandbox\";" | sudo -u postgres psql -f -
    ;;
  sqlite3)
    # Later: use something like:
    # sqlite:///$DATA_DIR/libeufin.db
    # But for now, sqlite is unsupported:
    echo "Unsupported database type $dbc_type."
    exit 1
    ;;
  "") ;;

  *)
    echo "Unsupported database type $dbc_type."
    exit 1
    ;;
  esac
fi
